import { v4 as uuid } from "uuid";

export const projectData = [
  {
    id: uuid(),
    title: "COUNTRY DATA FETCHER ",
    image: "./assets/country-data-app.png",
    description: "Find important data about any country",
    stacks: ["TypeScript", "React", "CSS"],
    liveSite: "https://country-data.tonnipaul.com/",
    github: "https://github.com/TonniPaul/Country-Data",
    design: "FrontEndMentor, TonniPaul",
  },
  {
    id: uuid(),
    title: "E-COMMERCE WEBSITE",
    image: "./assets/ltbws.png",
    description: "An online store selling baby and kids wears and accessories",
    stacks: ["WordPress", "CSS"],
    liveSite: "https://babywears.ng",
    github: "",
    hiddenClass: "hiddenClass",
    design: "TonniPaul",
  },
  {
    id: uuid(),
    title: "TO-DO WEB",
    image: "./assets/todo.png",
    description: "Create and manage Tasks or to-do lists. ",
    stacks: ["React", "CSS", "FontAwesome Icons"],
    liveSite: "https://todo.tonnipaul.com",
    github: "https://github.com/TonniPaul/Todo-App-/",
    design: "TonniPaul",
  },
  {
    id: uuid(),
    title: "PORTFOLIO WEBSITE",
    image: "./assets/portfolio.png",
    description: "My personal website",
    stacks: ["React", "CSS", "Framer Motion", "MUI Icons"],
    liveSite: "https://tonnipaul.com",
    github: "https://github.com/TonniPaul/portfolion",
    design: "TonniPaul (Inspo: Twitter & Dribble)",
  },

  {
    id: uuid(),
    title: "ADVICE GENERATOR",
    image: "./assets/advicegen.jpg",
    description: "An API-driven advice generator web application",
    stacks: ["React", "CSS", "API"],
    liveSite: "https://advice-generator-rho-six.vercel.app/",
    github: "https://github.com/TonniPaul/adviceGenerator",
    design: "FrontEnd Mentor",
  },
  {
    id: uuid(),
    title: "MUSICA (Music App Template)",
    image: "./assets/musica.png",
    description:
      "A Music Application template, (Implemented the search feature )",
    stacks: ["React", "CSS", "Rapid API", "Framer Motion"],
    liveSite: "https://musicabytonnipaul.vercel.app/",
    github: "https://github.com/tonniPaul/musica",
    design: "#360CODINGCHALLENGE 0n Twitter",
  },
  {
    id: uuid(),
    title: "CHATSCRUM",
    image: "./assets/chatscrum.png",
    description:
      "Web-based task organization application features drag-and-drop functionality",
    stacks: ["React", "CSS", "API"],
    liveSite: "http://prello-six.vercel.app/",
    github: "https://github.com/tonniPaul/prello",
    design: "LinuxJobber",
  },
  {
    id: uuid(),
    title: "MEME GENERATOR",
    image: "./assets/memelarge.png",
    description: "Generate Random Meme Image and Add your personalized caption",
    stacks: ["React", "CSS"],
    liveSite: "https://tonnimeme.vercel.app",
    github: "https://github.com/TonniPaul/meme",
    design: "Scrimba",
  },
  {
    id: uuid(),
    title: "DICE GAME",
    image: "./assets/dicegame.png",
    description:
      "The dice game generates random dice numbers and declares the winner when clicked",
    stacks: ["HTML", "CSS", "JavaScript"],
    liveSite: "https://tonnipaul.github.io/dice-game/",
    github: "https://github.com/TonniPaul/dice-game",
    design: "Angela Yu (UDEMY)",
  },
  {
    id: uuid(),
    title: "FITNESS WEBSITE TEMPLATE",
    image: "./assets/fitnesssite.png",
    description: "This is a fitness website template.",
    liveSite: "https://tonnipaul.github.io/My-gridisite/",
    stacks: ["React", "CSS", "UnSplash Images"],
    github: "https://github.com/TonniPaul/My-gridisite",
    design: "Travasery Media (Youtube)",
  },
  {
    id: uuid(),
    title: "Landing Page",
    image: "./assets/web-dev.png",
    description: "Landing Page for a web developer",
    stacks: ["HTML", "CSS", "BootStrap"],
    liveSite: "https://tonnipaulweb.vercel.app/",
    github: "https://github.com/TonniPaul/tonnipaulweb",
    design: "Angela Yu (UDEMY)",
  },
];
